version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - my_volume:/app/public/images/

volumes:
  my_volume:
